<?php

/**
 * @file
 * Contains gcnotify.module.
 */

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\gcnotify\Utils\NotificationAPIHandler;
use GuzzleHttp\Client;


/**
 * Implements hook_help().
 */
function gcnotify_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gcnotify module.
    case 'help.page.gcnotify':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integrate GC Notify service with Drupal for messaging') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 * save notification details from GC Notify API
 */
function gcnotify_cron() {

  // 1. get all records from gcnotify table for past 10 days

  $timestamp = (new DrupalDateTime())->getTimestamp();
  $database = \Drupal::service('database');
  $db_notifications = $database->select('gcnotify', 'g')
    ->fields('g')
    ->condition('g.callback_received', $timestamp - (86400 * 10), '>=')
    ->execute()
    ->fetchAll();

  // 2. get all notifications from GC Notify API

  $notify = new NotificationAPIHandler();
  $api_notifications = $notify->getEmailNotifications();

  // 3. match notification id and update

  foreach($api_notifications as $api_notification) {

    foreach($db_notifications as $db_notification) {

      if ($api_notification['id'] == $db_notification->id) {

        // 4. save response

        $database->update('gcnotify')
          ->fields([
            'status' => $api_notification['status'],
            'api_response' => json_encode($api_notification,
              JSON_PRETTY_PRINT
              | JSON_UNESCAPED_UNICODE
              | JSON_UNESCAPED_SLASHES
              | JSON_UNESCAPED_LINE_TERMINATORS),
            'api_response_date' => $timestamp,
            ])
          ->condition('id', $api_notification['id'], '=')
          ->execute();

      }

    }

  }

  \Drupal::logger('gcnotify')->notice('Completed update of notifications from GC Notify API');

}
