<?php

use \Drupal\og_ext_cron\Utils\CronFunctions;

/**
* @file
* Contains og_ext_cron.module.
*/

/**
 * Implements hook_cron().
 */
function og_ext_cron_cron() {

  $cron_tasks = new CronFunctions;

  // clear proactive disclosure view caches
  $cron_tasks->clearViewCaches();

  // export suggested datasets
  $cron_tasks->exportSuggestedDatasets();

  // export dataset ratings
  $cron_tasks->exportCumulativeDatasetRatings();

  // generate ATI informal requests CSV file
  $cron_tasks->generateAtiRequestsCsvFile();

  /* for development purpose only

  // fetch field lists from CKAN
  $fields = [
    'organizations' => 'records',
    'character_set' => 'resource_fields',
    'audience' => 'dataset_fields',
    'format' => 'resource_fields',
    'language' => 'resource_fields',
    'reason' => 'dataset_fields',
    'subject' => 'dataset_fields',
    'frequency' => 'dataset_fields',
    'resource_type' => 'resource_fields',
  ];

  foreach ($fields as $field => $type) {
    $cron_tasks->fetchFromCkan($field, $type);
  }
  */
}
