<?php

use Drupal\og_ext_cron\Utils\CronFunctions;

/**
* @file
* Contains og_ext_cron.module.
*/

/**
 * Implements hook_cron().
 * clear cache of views generated using Solr
 */
function og_ext_cron_cron() {
  // clear proactive disclosure view caches
  CronFunctions::clear_view_caches();
  gc_collect_cycles();

/*
  // fetch organizations list from CKAN
  CronFunctions::fetch_orgs_from_ckan();

  // fetch field lists from CKAN
  $fields = [
    'character_set' => 'resource_fields',
    'audience' => 'dataset_fields',
    'format' => 'resource_fields',
    'language' => 'resource_fields',
    'reason' => 'dataset_fields',
    'subject' => 'dataset_fields',
    'frequency' => 'dataset_fields',
    'resource_type' => 'resource_fields',
  ];

  foreach ($fields as $field => $type) {
    CronFunctions::fetch_from_ckan($field, $type);
  }
*/

  // export dataset comments
  CronFunctions::export_external_comments();
  gc_collect_cycles();

  // export dataset ratings
  CronFunctions::export_cumulative_dataset_ratings();
  gc_collect_cycles();

  // export suggested datasets
  CronFunctions::export_suggested_datasets();
  gc_collect_cycles();

  // generate inventory vote count json file
  CronFunctions::generate_vote_count_json_file();
  gc_collect_cycles();

  // generate ATI informal requests CSV file
  CronFunctions::generate_ati_requests_csv_file();
  gc_collect_cycles();
}
